algoritmo "Analista de Servidores"
// Disciplina  :  Algoritmos e Lógica de Programação
// Professor   : [Nome do Professor]
// Descrição   : O sistema lê o nome do servidor e o tempo de resposta em milissegundos informados pelo usuário no terminal, faz a média de tempo e gera uma fila, sendo que o servidor com maior tempo de resposta fica em primeiro, e o com menor tempo fica em último
// Autor(a)    : José Luiz Bruiani Barco
// Data atual  : ${05}/${10}/${2026}
var



inicio



fimalgoritmo